# Generated by Django 5.2.16 on 2026-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0003_optimizationhistory_prism_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizationhistory",
            name="is_executed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this optimization has been executed/applied",
            ),
        ),
    ]
