# Generated by Django 5.2.16 on 2026-07-10 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0004_add_is_executed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scrap_id", models.CharField(max_length=100, unique=True)),
                (
                    "parent_block_code",
                    models.CharField(help_text="e.g. B1", max_length=100),
                ),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("volume", models.FloatField()),
                (
                    "usability",
                    models.CharField(
                        choices=[
                            ("usable", "Usable"),
                            ("unusable", "Unusable"),
                            ("manual", "Manually Added"),
                        ],
                        default="usable",
                        max_length=20,
                    ),
                ),
                ("is_in_inventory", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_scraps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "optimization_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraps",
                        to="planner.optimizationhistory",
                    ),
                ),
            ],
            options={
                "db_table": "scrap_inventory",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["usability"], name="scrap_inven_usabili_04a92b_idx"
                    ),
                    models.Index(
                        fields=["parent_block_code"],
                        name="scrap_inven_parent__633005_idx",
                    ),
                    models.Index(
                        fields=["is_in_inventory"],
                        name="scrap_inven_is_in_i_336b89_idx",
                    ),
                ],
            },
        ),
    ]
